# Generated by Django 6.0.6 on 2026-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('OVERDUE', 'Impayée')], default='PENDING', max_length=10),
        ),
    ]
