# Generated by Django 6.0.6 on 2026-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
